title: My Website
description: "Website untuk berbagi artikel dan pemikiran."
author: "Putra Jaya"
url: "https://masputrawae.github.io" # Ganti dengan URL GitHub Pages kamu
baseurl: "/Mp-official" # Ganti jika menggunakan subfolder
markdown: kramdown
permalink: pretty
paginate: 5 # Jika ingin mempaginate artikel
