title: My Website
description: "Website untuk berbagi artikel dan pemikiran."
author: "Putra Jaya"
url: "http://localhost:4000" # Ganti dengan URL GitHub Pages kamu
baseurl: "" # Ganti jika menggunakan subfolder
markdown: kramdown
permalink: pretty
paginate: 5 # Jika ingin mempaginate artikel
